const images = {
  greenBackground: require('../assets/images/green-background.jpg'),
  appLogo: require('../assets/images/kmologo1.png'),
  weatherBackground: require('../assets/images/weather-bg.jpg'),
  fewClouds: require('../assets/images/sunny.png'),
  car: require('../assets/images/car.png'),
  notiflogo: require('../assets/images/sound.png'),
  passImage: require('../assets/images/kmoimg.jpg'),
  howToImg: require('../assets/images/Capture.png'),
  servicesImg1: require('../assets/images/default.jpg'),
  servicesImg2: require('../assets/images/kesim.jpg'),
  kmoLogo: require('../assets/images/kmologoSplash.png'),
  onBoardIcon: require('../assets/images/appIcon1.png'),
  carlogo: require('../assets/images/carlogo.png'),
  profileImg: require('../assets/images/interested-woman-with-wavy-hair-taking-selfie.jpg'),
  paymentPreview:require('../assets/images/paymentprev.png'),
  truck:require('../assets/images/truck.png'),
  van: require('../assets/images/van.png'),
  loginImage:require('../assets/images/5226-removebg-preview.png'),
  blueCar: require('../assets/images/tesla-blue.png'),
  redCar: require('../assets/images/tesla-red.png'),
  blackCar: require('../assets/images/tesla-black.png'),
  sunny:require('../assets/images/sunny-icon.png'),
  rainy:require('../assets/images/rainy-icon.png'),
  snowy:require('../assets/images/snowy-icon.png'),
  windy:require('../assets/images/windy-icon.png'),
  yellowMotor:require('../assets/images/motor-yellow.png'),
  blackMotor:require('../assets/images/motor-black.png'),
  blueMotor:require('../assets/images/motor-blue.png'),
  redMotor:require('../assets/images/motor-red.png'),
  clouds:require('../assets/images/clouds.png'),
  thunderstorm: require('../assets/images/thunderstorm.png'),
  failded: require('../assets/images/3675500.png')
};

export default images;
